# Build android workflow
name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Debug Application
          path: app/build/outputs/apk/debug/app-debug.apk
