# Build android workflow
name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        run: ./gradlew assembleDevDebug
      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: devDebug Application
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
